package:
  format-version: "1.0.0"
  name: "gfx_apps_pic32cz_ca70_mc70"
  version: "v1.0.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "gfx"
      type: "package"
      version: "v3.15.1"
    - name: "csp"
      type: "package"
      version: "v3.19.0"
    - name: "bsp"
      type: "package"
      version: "v3.20.0"
